<a href="https://colab.research.google.com/github/JayDock/My-journey-to-Machine-Learning/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy is a general purpose array processing laguage..

In [1]:
import numpy as np

In [3]:
my_list = [1, 2, 3, 4]
arr = np.array(my_list)

In [4]:
type(arr)

numpy.ndarray

In [6]:
print(arr)

[1 2 3 4]


In [7]:
arr.shape

(4,)

In [15]:
#Multidimensional array

my_list1 = [1,2,3,4,5]
my_list2 = [2, 4, 5,1, 7]
my_list3 = [4,6,1,9,5]

arr = np.array([my_list1, my_list2, my_list3])
arr

array([[1, 2, 3, 4, 5],
       [2, 4, 5, 1, 7],
       [4, 6, 1, 9, 5]])

In [12]:
arr.shape

(3, 5)

In [13]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [4, 5, 1],
       [7, 4, 6],
       [1, 9, 5]])

# **Indexing**

In [14]:
my_list = [1, 2, 3, 4, 5, 6, 7]
arr = np.array(my_list)
arr[4]

5

In [17]:
print(arr)

[[1 2 3 4 5]
 [2 4 5 1 7]
 [4 6 1 9 5]]


In [18]:
arr[:,:]

array([[1, 2, 3, 4, 5],
       [2, 4, 5, 1, 7],
       [4, 6, 1, 9, 5]])

In [19]:
arr[1:,0:2]

array([[2, 4],
       [4, 6]])

In [20]:
arr[:,3:]

array([[4, 5],
       [1, 7],
       [9, 5]])

In [21]:
print(arr)

[[1 2 3 4 5]
 [2 4 5 1 7]
 [4 6 1 9 5]]


In [22]:
arr[1:,2:4]

array([[5, 1],
       [1, 9]])

In [23]:
arr[1:,0:2]

array([[2, 4],
       [4, 6]])

#in-built functions in numpy

# **arrange()**

In [26]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr = np.arange(0,10,step = 2)
arr

array([0, 2, 4, 6, 8])

In [30]:
arr = np.linspace(1, 10,50)
arr

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

# **copy()function and broadcating**

In [33]:
arr = [1, 2, 3, 4,5,6,7,8,9]
arr = np.array(arr)
arr[3:] =100
arr

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [34]:
arr1 = arr
arr1[3:] = 500
arr1

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [35]:
arr

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

Here in above snippet codes, any chane in one array affects the other array,........so we can prevent this by using copy() as shon below

In [36]:
arr1 = arr.copy()

In [37]:
print(arr)
arr1[3:] = 1000
print(arr1)

[  1   2   3 500 500 500 500 500 500]
[   1    2    3 1000 1000 1000 1000 1000 1000]


# **some conditions very useful in Exploratory Data Analysis**

In [39]:
val = 2
arr<2
arr[arr<200]

array([1, 2, 3])

Create arrays and reshape

In [40]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [42]:
arr1 = np.arange(0,10).reshape(2,5)
arr2 = np.arange(0,10).reshape(2,5)
arr1*arr2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [43]:
np.ones(4)

array([1., 1., 1., 1.])

In [46]:
np.ones(4, dtype = int)

array([1, 1, 1, 1])

In [48]:
np.ones((2,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

Random distribution

In [49]:
np.random.rand(3,3)

array([[0.73536031, 0.04593364, 0.49966085],
       [0.34579736, 0.28166204, 0.33923649],
       [0.04977953, 0.37948328, 0.66646786]])

In [51]:
arr_ex = np.random.randn(4,4)
arr_ex

array([[ 0.43049315, -0.86482934, -0.47456351, -1.4060624 ],
       [-1.23924883,  1.41893591,  0.65522889,  0.15810888],
       [-1.52452247,  2.58370643,  1.02586061,  0.25758402],
       [-1.49395881,  1.11957248,  0.48941239, -0.25424404]])